client:
  id: knarkscan
  subscribe_root_topic: knark/nvr/+/motion
  publish_root_topic: knark/scan
  video_stream_base_url: rtsp://localhost:8554/
  scan_snapshot: True
  scan_barcode: True
  scan_datamatrix: True
  scan_datamatrix_timeout: 200
  scan_datamatrix_max_count: 3
  snapshot_file_prefix: knarkscan
  snapshot_path: ./snapshot

mqtt:
  host: 127.0.0.1
  port: 1883
  username: are
  password: test123

